version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
#   BeforeInstall:
#     - location: beforeinstall.sh
#       timeout: 1000
  AfterInstall:
    - location: afterinstall.sh
      timeout: 100
  ApplicationStart:
    - location: applicationstart.sh
      timeout: 1000
